const $=id=>document.getElementById(id);let activeId=null;
async function api(path,options={}){const r=await fetch(path,{headers:{"content-type":"application/json"},...options});const j=await r.json();if(!r.ok)throw Error(j.error||"Something went wrong.");return j}
function safe(value){const n=document.createElement("span");n.textContent=value||"";return n.innerHTML}
function renderList(ideas){$("idea-count").textContent=ideas.length;$("idea-list").innerHTML=ideas.length?ideas.map(i=>`<button class="idea-item ${i.id===activeId?"selected":""}" data-id="${i.id}"><strong>${safe(i.name)}</strong><span>${i.score}/100 · ${new Date(i.updatedAt).toLocaleDateString()}</span></button>`).join(""):"<p class=empty>Your saved ideas will appear here.</p>";document.querySelectorAll(".idea-item").forEach(b=>b.onclick=()=>loadIdea(b.dataset.id))}
async function loadList(){try{renderList(await api("/api/ideas"))}catch(e){console.error(e)}}
function show(i){activeId=i.id;$("intake").hidden=true;$("output").hidden=false;$("title").textContent=i.name;$("score").textContent=i.score;$("verdict").textContent=i.verdict;$("summary").textContent=i.summary;$("scorecards").innerHTML=i.scoreBreakdown.map(x=>`<article><span>${safe(x.label)}</span><strong>${x.score}/20</strong><p>${safe(x.reason)}</p></article>`).join("");$("next-steps").innerHTML=i.nextSteps.map(x=>`<li>${safe(x)}</li>`).join("");$("build-prompt").textContent=i.buildPrompt;loadList()}
async function loadIdea(id){try{show(await api(`/api/ideas/${id}`))}catch(e){alert(e.message)}}
$("idea-form").onsubmit=async e=>{e.preventDefault();const b=$("start");b.disabled=true;b.textContent="Creating workspace…";try{show(await api("/api/ideas",{method:"POST",body:JSON.stringify({idea:$("idea").value.trim(),audience:$("audience").value.trim(),budget:$("budget").value.trim(),problem:$("problem").value.trim(),alternatives:$("alternatives").value.trim(),advantage:$("advantage").value.trim()})}))}catch(e){alert(e.message)}finally{b.disabled=false;b.innerHTML="Create idea workspace <span>→</span>"}};
$("new-idea").onclick=()=>{activeId=null;$("idea-form").reset();$("output").hidden=true;$("intake").hidden=false;loadList();$("idea").focus()};$("copy-prompt").onclick=async()=>{await navigator.clipboard.writeText($("build-prompt").textContent);$("copy-prompt").textContent="Copied";setTimeout(()=>$("copy-prompt").textContent="Copy build prompt",1400)};loadList();
