// Mock data for development — replace with real API calls
import type { VisualSearchResult, TrendCard, Product, ProductVariant } from "./types";
import type { ReviewsData } from "@/components/product/ReviewSummary";

export const MOCK_TREND_CARDS: TrendCard[] = [
  { id: "t1", aesthetic: "quiet_luxury",  label: "Quiet Luxury",   cover_image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&q=80", save_count: 8470,  product_count: 234 },
  { id: "t2", aesthetic: "artisan_craft", label: "Artisan Craft",  cover_image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400&q=80",  save_count: 12400, product_count: 189 },
  { id: "t3", aesthetic: "y2k",           label: "Y2K Revival",    cover_image: "https://images.unsplash.com/photo-1594938298603-c8148c4f4f3c?w=400&q=80",  save_count: 23100, product_count: 412 },
  { id: "t4", aesthetic: "japandi",       label: "Japandi Home",   cover_image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80",      save_count: 6890,  product_count: 156 },
];

const MOCK_SELLER_ARTISAN = {
  id: "s1", name: "Kalakar Crafts", type: "artisan" as const,
  city: "Jaipur", is_verified: true, is_local: true, rating: 4.7,
};

const MOCK_SELLER_BRAND = {
  id: "s2", name: "Nilkamal Home", type: "brand" as const,
  is_verified: true, is_local: false, rating: 4.2,
};

const MOCK_SELLER_D2C = {
  id: "s3", name: "The Label Studio", type: "d2c" as const,
  city: "Delhi", is_verified: true, is_local: true, rating: 4.8,
};

const MOCK_SELLER_LOCAL = {
  id: "s4", name: "Artisan Weaves", type: "artisan" as const,
  city: "Pune", is_verified: true, is_local: true, rating: 4.6,
};

// ─── Full product detail mock (existing, used as detail page default) ─────────

export const MOCK_PRODUCT_VARIANTS: ProductVariant[] = [
  { id: "v-xs", size: "XS", price: 2499, mrp: 4999, stock_count: 3 },
  { id: "v-s",  size: "S",  price: 2499, mrp: 4999, stock_count: 8 },
  { id: "v-m",  size: "M",  price: 2499, mrp: 4999, stock_count: 12 },
  { id: "v-l",  size: "L",  price: 2499, mrp: 4999, stock_count: 5 },
  { id: "v-xl", size: "XL", price: 2499, mrp: 4999, stock_count: 0 },
];

export const MOCK_PRODUCT_DETAIL: Product & {
  description: string;
  material_details: string[];
  care_instructions: string[];
  ships_in_days: string;
  aesthetic_codes: string[];
} = {
  id: "sv1",
  title: "Sage Green Linen Co-ord Set",
  description: "Effortlessly elevated. Our linen co-ord set is cut from 100% Indian linen sourced from Vidarbha. The blazer has a relaxed single-button closure; the wide-leg trousers feature a drawstring waist. A better alternative to the Zara linen set at 31% of the price.",
  category: "fashion",
  images: [
    "https://images.unsplash.com/photo-1594938298603-c8148c4f4f3c?w=800&q=80",
    "https://images.unsplash.com/photo-1571513800374-df1bbe650e56?w=800&q=80",
    "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80",
    "https://images.unsplash.com/photo-1544816565-aa8c1166648f?w=800&q=80",
  ],
  price: 2499,
  mrp: 4999,
  currency: "INR",
  seller: {
    id: "s-label", name: "The Label Studio", type: "d2c",
    city: "Delhi", is_verified: true, is_local: true, rating: 4.8,
  },
  rating: 4.6,
  review_count: 847,
  similarity_score: 91,
  similarity_tier: "smart_value",
  similarity_breakdown: { shape: 94, color: 96, material: 89, style: 88, overall: 91 },
  aesthetic_codes: ["quiet_luxury", "clean_girl", "minimal"],
  original_ref: { name: "Linen Blazer Co-ord Set", brand: "Zara", price: 7999 },
  ai_explanation: {
    verdict: "excellent_value",
    headline: "91% of the Zara look at 31% of the price.",
    what_matches: ["Same Indian linen source", "Identical relaxed blazer silhouette", "Wide-leg trouser cut matches closely"],
    what_differs: ["Blazer has slightly less internal structure — better for casual, slightly less formal", "No Zara logo (pro for most people)"],
    ai_recommendation: "For casual or office-casual wear, you will not notice the difference. Save ₹5,500.",
  },
  material_details: [
    "100% Linen (Vidarbha, India)",
    "Hand-finished seams",
    "Single-button blazer closure",
    "Drawstring waist trousers",
    "Unlined (breathable for Indian summers)",
  ],
  care_instructions: ["Machine wash cold (30°C)", "Do not tumble dry", "Iron on medium heat", "Dry in shade"],
  ships_in_days: "2-3 business days",
  variants: MOCK_PRODUCT_VARIANTS,
};

// ─── Extended product catalogue ───────────────────────────────────────────────

export const MOCK_PRODUCTS: Product[] = [
  // ── Quiet Luxury ──────────────────────────────────────────────────────────
  {
    id: "p_ql_1",
    title: "Sage Green Linen Blazer Set",
    description: "Relaxed linen co-ord for the effortlessly elevated wardrobe.",
    category: "fashion",
    images: ["https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=80"],
    price: 2499, mrp: 4999, currency: "INR",
    seller: MOCK_SELLER_D2C, rating: 4.7, review_count: 412,
    aesthetic_codes: ["quiet_luxury"],
    similarity_score: 91, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 94, color: 96, material: 89, style: 90, overall: 91 },
    original_ref: { name: "Linen Blazer Coord Set", brand: "Zara", price: 7999 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "91% of the Zara look at 31% of the price.",
      what_matches: ["Same Indian linen fabric", "Identical relaxed silhouette", "Wide-leg trouser cut"],
      what_differs: ["Slightly less internal structure", "No Zara label"],
      ai_recommendation: "For office-casual, you won't notice the difference. Save ₹5,500.",
    },
    material_details: ["100% Linen (Vidarbha, India)", "Hand-finished seams", "Drawstring waist"],
    care_instructions: ["Machine wash cold 30°C", "Do not tumble dry", "Iron medium heat"],
    ships_in_days: "2-3 business days",
    variants: [
      { id: "v-xs", size: "XS", price: 2499, mrp: 4999, stock_count: 3 },
      { id: "v-s",  size: "S",  price: 2499, mrp: 4999, stock_count: 8 },
      { id: "v-m",  size: "M",  price: 2499, mrp: 4999, stock_count: 12 },
      { id: "v-l",  size: "L",  price: 2499, mrp: 4999, stock_count: 5 },
    ],
  },
  {
    id: "p_ql_2",
    title: "Ivory Cashmere-Touch Stole",
    description: "Buttery soft stole that drapes like cashmere at a fraction of the price.",
    category: "fashion",
    images: ["https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=600&q=80"],
    price: 1850, mrp: 3500, currency: "INR",
    seller: MOCK_SELLER_ARTISAN, rating: 4.6, review_count: 289,
    aesthetic_codes: ["quiet_luxury"],
    similarity_score: 87, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 88, color: 92, material: 85, style: 86, overall: 87 },
    original_ref: { name: "Cashmere Scarf", brand: "Massimo Dutti", price: 8500 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Cashmere blend at merino prices.",
      what_matches: ["Same buttery drape", "Classic ivory tone", "Generous wrap dimensions"],
      what_differs: ["Wool-cashmere blend vs pure cashmere", "Slightly less weight"],
      ai_recommendation: "78% cheaper — barely distinguishable at arm's length.",
    },
    material_details: ["70% Merino Wool, 30% Cashmere Blend", "Hand-loomed in Ludhiana"],
    care_instructions: ["Hand wash cold", "Dry flat", "Low iron"],
    ships_in_days: "3-4 business days",
  },
  {
    id: "p_ql_3",
    title: "Gold Vermeil Minimal Hoop Earrings",
    description: "Delicate everyday hoops in gold vermeil finish.",
    category: "beauty",
    images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80"],
    price: 1299, mrp: 2000, currency: "INR",
    seller: MOCK_SELLER_D2C, rating: 4.8, review_count: 874,
    aesthetic_codes: ["quiet_luxury"],
    similarity_score: 94, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 97, color: 95, material: 90, style: 95, overall: 94 },
    original_ref: { name: "Mini Hoop Earrings", brand: "Mejuri", price: 6200 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Near-identical look. 79% cheaper.",
      what_matches: ["Same 18mm hoop diameter", "Gold vermeil finish", "Huggie-style closure"],
      what_differs: ["925 silver base vs gold-fill", "Hallmark differs"],
      ai_recommendation: "For everyday wear, identical look. Save ₹4,900.",
    },
    material_details: ["925 Sterling Silver", "18k Gold Vermeil coating", "Hypoallergenic posts"],
    care_instructions: ["Wipe with soft cloth", "Store dry", "Avoid perfume contact"],
    ships_in_days: "1-2 business days",
  },
  {
    id: "p_ql_4",
    title: "Silk-Touch Satin Camisole — Blush",
    description: "Bias-cut satin cami with adjustable straps — a wardrobe essential.",
    category: "fashion",
    images: ["https://images.unsplash.com/photo-1589465885857-44edb59bbff2?w=600&q=80"],
    price: 1499, mrp: 2800, currency: "INR",
    seller: MOCK_SELLER_D2C, rating: 4.5, review_count: 631,
    aesthetic_codes: ["quiet_luxury"],
    similarity_score: 88, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 90, color: 94, material: 83, style: 88, overall: 88 },
    original_ref: { name: "Satin Cami", brand: "& Other Stories", price: 4500 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Same silky look, 67% cheaper.",
      what_matches: ["Adjustable spaghetti straps", "Bias-cut drape", "Blush tone match"],
      what_differs: ["Polyester satin vs silk-blend", "Slightly less slippery hand-feel"],
      ai_recommendation: "Excellent for layering or standalone. Save ₹3,000.",
    },
    material_details: ["100% Polyester Satin", "Adjustable straps", "Side seam invisible zip"],
    care_instructions: ["Machine wash delicate", "Cool iron or steam"],
    ships_in_days: "2-3 business days",
    variants: [
      { id: "v-xs", size: "XS", price: 1499, mrp: 2800, stock_count: 5 },
      { id: "v-s",  size: "S",  price: 1499, mrp: 2800, stock_count: 9 },
      { id: "v-m",  size: "M",  price: 1499, mrp: 2800, stock_count: 7 },
    ],
  },
  {
    id: "p_ql_5",
    title: "Wide-Leg Linen Trousers — Oatmeal",
    description: "High-rise wide-leg trousers in a linen-viscose blend.",
    category: "fashion",
    images: ["https://images.unsplash.com/photo-1571513800374-df1bbe650e56?w=600&q=80"],
    price: 1899, mrp: 3500, currency: "INR",
    seller: MOCK_SELLER_D2C, rating: 4.6, review_count: 502,
    aesthetic_codes: ["quiet_luxury"],
    similarity_score: 89, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 92, color: 90, material: 87, style: 88, overall: 89 },
    original_ref: { name: "Wide Leg Linen Pants", brand: "Arket", price: 6800 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Same Scandinavian silhouette. 72% cheaper.",
      what_matches: ["High-rise waistband", "Relaxed wide-leg cut", "Natural oatmeal colour"],
      what_differs: ["Single-crease front vs double", "Zip fly vs button"],
      ai_recommendation: "Almost impossible to tell apart in photos. Buy this.",
    },
    material_details: ["55% Linen, 45% Viscose blend", "High-rise cut", "Elasticated back waist"],
    care_instructions: ["Machine wash 30°C", "Tumble dry low", "Iron while slightly damp"],
    ships_in_days: "2-3 business days",
    variants: [
      { id: "v-xs", size: "XS", price: 1899, mrp: 3500, stock_count: 4 },
      { id: "v-s",  size: "S",  price: 1899, mrp: 3500, stock_count: 10 },
      { id: "v-m",  size: "M",  price: 1899, mrp: 3500, stock_count: 7 },
      { id: "v-l",  size: "L",  price: 1899, mrp: 3500, stock_count: 3 },
    ],
  },

  // ── Artisan Craft ─────────────────────────────────────────────────────────
  {
    id: "p_ac_1",
    title: "Ajrakh Block Print Kurta — Indigo",
    description: "Authentic Kutch Ajrakh with natural indigo dye. Direct from the artisan.",
    category: "fashion",
    images: ["https://images.unsplash.com/photo-1605289982774-9a6fef564df8?w=600&q=80"],
    price: 1299, mrp: 2200, currency: "INR",
    seller: MOCK_SELLER_ARTISAN, rating: 4.8, review_count: 763,
    aesthetic_codes: ["artisan_craft"],
    similarity_score: 95, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 96, color: 97, material: 94, style: 95, overall: 95 },
    original_ref: { name: "Ajrakh Block Print Kurta", brand: "Fabindia", price: 3200 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Same artisan technique. 59% cheaper, direct from maker.",
      what_matches: ["Authentic Ajrakh hand-printing", "Same natural indigo dye", "Relaxed A-line cut"],
      what_differs: ["No Fabindia label — this is the actual artisan"],
      ai_recommendation: "You're buying from the Kutch craftsperson directly. Better provenance, lower price.",
    },
    material_details: ["100% Kala Cotton", "Natural Ajrakh block print", "Hand-dyed with natural indigo"],
    care_instructions: ["Hand wash cold", "Dry in shade", "Separate colours first wash"],
    ships_in_days: "3-5 business days",
    variants: [
      { id: "v-s",  size: "S",  price: 1299, mrp: 2200, stock_count: 6 },
      { id: "v-m",  size: "M",  price: 1299, mrp: 2200, stock_count: 9 },
      { id: "v-l",  size: "L",  price: 1299, mrp: 2200, stock_count: 4 },
      { id: "v-xl", size: "XL", price: 1299, mrp: 2200, stock_count: 2 },
    ],
  },
  {
    id: "p_ac_2",
    title: "Handwoven Chanderi Silk Saree",
    description: "Pure Chanderi silk saree with traditional gold zari border.",
    category: "fashion",
    images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80"],
    price: 2800, mrp: 5500, currency: "INR",
    seller: MOCK_SELLER_LOCAL, rating: 4.9, review_count: 341,
    aesthetic_codes: ["artisan_craft"],
    similarity_score: 97, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 98, color: 97, material: 96, style: 97, overall: 97 },
    original_ref: { name: "Chanderi Silk Saree", brand: "Taneira", price: 8500 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Direct from Chanderi weavers. 67% cheaper than Taneira.",
      what_matches: ["Authentic Chanderi silk", "Same sheer tissue-thin texture", "Traditional gold zari border"],
      what_differs: ["No retail markup", "Comes without branded packaging"],
      ai_recommendation: "Same weaver clusters. Same craft. Buy direct, skip retail premium.",
    },
    material_details: ["Pure Chanderi Silk", "Real zari border", "6 yards with running blouse"],
    care_instructions: ["Dry clean only", "Store in muslin", "Avoid moisture"],
    ships_in_days: "4-5 business days",
  },
  {
    id: "p_ac_3",
    title: "Blue Pottery Chai Mug Set (4 pcs)",
    description: "Authentic Jaipur blue pottery — each piece hand-crafted and unique.",
    category: "home",
    images: ["https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=600&q=80"],
    price: 899, mrp: 1600, currency: "INR",
    seller: MOCK_SELLER_ARTISAN, rating: 4.7, review_count: 1204,
    aesthetic_codes: ["artisan_craft"],
    similarity_score: 92, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 93, color: 94, material: 90, style: 92, overall: 92 },
    original_ref: { name: "Blue Pottery Mugs (4pcs)", brand: "Noritake India", price: 2800 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Authentic Jaipur craft. 68% cheaper.",
      what_matches: ["Traditional blue pottery technique", "Same cobalt floral motifs", "Identical 300ml capacity"],
      what_differs: ["Artisan variation means no two are identical — that's the point"],
      ai_recommendation: "Same craftspeople. Better story, better price.",
    },
    material_details: ["Quartz clay base", "Natural cobalt glazing", "Food-safe finish"],
    care_instructions: ["Hand wash only", "Not microwave safe", "Dry immediately"],
    ships_in_days: "3-4 business days",
  },
  {
    id: "p_ac_4",
    title: "Genuine Kolhapuri Chappal — Tan",
    description: "GI-tagged Kolhapuri cow leather sandals with traditional hand-punched pattern.",
    category: "fashion",
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80"],
    price: 1199, mrp: 2000, currency: "INR",
    seller: MOCK_SELLER_LOCAL, rating: 4.6, review_count: 589,
    aesthetic_codes: ["artisan_craft"],
    similarity_score: 96, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 97, color: 95, material: 97, style: 96, overall: 96 },
    original_ref: { name: "Kolhapuri Sandals", brand: "Good Earth", price: 3800 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "GI-tagged Kolhapuri, direct from craftspeople. 68% cheaper.",
      what_matches: ["Genuine GI-tagged Kolhapuri leather", "Traditional hand-punched pattern", "Layered sole construction"],
      what_differs: ["No boutique retail tag"],
      ai_recommendation: "Same GI designation as Good Earth sells. You're paying only for the craft.",
    },
    material_details: ["GI-tagged Kolhapuri cow leather", "Hand-punched floral tooling", "Multi-layer leather sole"],
    care_instructions: ["Apply leather conditioner monthly", "Avoid prolonged water exposure"],
    ships_in_days: "3-5 business days",
    variants: [
      { id: "v-5",  size: "5",  price: 1199, mrp: 2000, stock_count: 3 },
      { id: "v-6",  size: "6",  price: 1199, mrp: 2000, stock_count: 7 },
      { id: "v-7",  size: "7",  price: 1199, mrp: 2000, stock_count: 8 },
      { id: "v-8",  size: "8",  price: 1199, mrp: 2000, stock_count: 4 },
    ],
  },
  {
    id: "p_ac_5",
    title: "Indigo Kantha Stole — Hand-stitched",
    description: "SHG-made Kantha stole with natural indigo dye on mulmul cotton.",
    category: "fashion",
    images: ["https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=600&q=80"],
    price: 950, mrp: 1800, currency: "INR",
    seller: MOCK_SELLER_ARTISAN, rating: 4.8, review_count: 432,
    aesthetic_codes: ["artisan_craft"],
    similarity_score: 93, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 94, color: 95, material: 92, style: 92, overall: 93 },
    original_ref: { name: "Kantha Embroidery Stole", brand: "Craftsvilla", price: 2500 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "SHG-made Kantha. 62% cheaper, 100% authentic.",
      what_matches: ["Authentic running-stitch Kantha", "Natural indigo hand-dye", "Double-layer mulmul cotton"],
      what_differs: ["No platform curation — direct from Murshidabad SHG"],
      ai_recommendation: "Proceeds go directly to the women's cooperative. Better impact, better price.",
    },
    material_details: ["Mulmul cotton base", "Natural indigo dye", "Hand-stitched Kantha work"],
    care_instructions: ["Hand wash cold", "Dry in shade", "Light iron"],
    ships_in_days: "4-6 business days",
  },

  // ── Y2K ───────────────────────────────────────────────────────────────────
  {
    id: "p_y2k_1",
    title: "Low-Rise Cargo Jeans — Washed Blue",
    description: "Y2K-era low-rise cargo jeans with side pockets in washed denim.",
    category: "fashion",
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4f4f3c?w=600&q=80"],
    price: 1699, mrp: 3000, currency: "INR",
    seller: MOCK_SELLER_BRAND, rating: 4.4, review_count: 2341,
    aesthetic_codes: ["y2k"],
    similarity_score: 86, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 88, color: 90, material: 82, style: 88, overall: 86 },
    original_ref: { name: "Low-Rise Cargo Jeans", brand: "BDG Urban Outfitters", price: 5200 },
    ai_explanation: {
      verdict: "good_match",
      headline: "Same Y2K silhouette. 67% cheaper.",
      what_matches: ["Low-rise waist cut", "Side cargo pockets", "Washed blue denim look"],
      what_differs: ["Slightly less stretch", "Lighter denim weight"],
      ai_recommendation: "Great for the trend. Save ₹3,500.",
    },
    material_details: ["75% Cotton, 20% Polyester, 5% Elastane", "5-pocket + 2 cargo pockets"],
    care_instructions: ["Machine wash cold", "Tumble dry low", "Do not bleach"],
    ships_in_days: "2-4 business days",
    variants: [
      { id: "v-26", size: "26", price: 1699, mrp: 3000, stock_count: 5 },
      { id: "v-28", size: "28", price: 1699, mrp: 3000, stock_count: 8 },
      { id: "v-30", size: "30", price: 1699, mrp: 3000, stock_count: 6 },
      { id: "v-32", size: "32", price: 1699, mrp: 3000, stock_count: 3 },
    ],
  },
  {
    id: "p_y2k_2",
    title: "Platform Chunky Sandals — Black",
    description: "3-inch platform block sandals with adjustable ankle strap.",
    category: "fashion",
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80"],
    price: 1499, mrp: 2800, currency: "INR",
    seller: MOCK_SELLER_BRAND, rating: 4.3, review_count: 1087,
    aesthetic_codes: ["y2k"],
    similarity_score: 83, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 85, color: 90, material: 78, style: 84, overall: 83 },
    original_ref: { name: "Platform Sandals", brand: "Steve Madden", price: 5500 },
    ai_explanation: {
      verdict: "good_match",
      headline: "Same platform aesthetic. 73% cheaper.",
      what_matches: ["3-inch platform sole", "Chunky block heel", "Adjustable ankle strap"],
      what_differs: ["Faux leather vs genuine", "Slightly less cushioning"],
      ai_recommendation: "For occasional wear, indistinguishable. Save ₹4,000.",
    },
    material_details: ["PU upper", "Rubber sole", "3-inch platform + 1-inch heel"],
    care_instructions: ["Wipe clean with damp cloth", "Store in box"],
    ships_in_days: "2-4 business days",
    variants: [
      { id: "v-5", size: "5", price: 1499, mrp: 2800, stock_count: 4 },
      { id: "v-6", size: "6", price: 1499, mrp: 2800, stock_count: 7 },
      { id: "v-7", size: "7", price: 1499, mrp: 2800, stock_count: 5 },
      { id: "v-8", size: "8", price: 1499, mrp: 2800, stock_count: 2 },
    ],
  },
  {
    id: "p_y2k_3",
    title: "Metallic Mini Skirt — Silver",
    description: "Bodycon metallic mini skirt with elasticated waistband.",
    category: "fashion",
    images: ["https://images.unsplash.com/photo-1589465885857-44edb59bbff2?w=600&q=80"],
    price: 899, mrp: 1800, currency: "INR",
    seller: MOCK_SELLER_BRAND, rating: 4.2, review_count: 876,
    aesthetic_codes: ["y2k"],
    similarity_score: 85, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 87, color: 88, material: 80, style: 86, overall: 85 },
    original_ref: { name: "Metallic Mini Skirt", brand: "H&M", price: 2999 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Same disco-era look. 70% cheaper.",
      what_matches: ["Metallic silver fabric", "Bodycon mini cut", "Elasticated waistband"],
      what_differs: ["Slightly less metallic sheen", "Polyester vs metallic yarn"],
      ai_recommendation: "For one-season trend wear, save ₹2,100.",
    },
    material_details: ["100% Polyester metallic weave", "Stretch fabric", "Side zip"],
    care_instructions: ["Hand wash cold", "Do not wring", "Line dry"],
    ships_in_days: "2-3 business days",
    variants: [
      { id: "v-xs", size: "XS", price: 899, mrp: 1800, stock_count: 6 },
      { id: "v-s",  size: "S",  price: 899, mrp: 1800, stock_count: 9 },
      { id: "v-m",  size: "M",  price: 899, mrp: 1800, stock_count: 7 },
    ],
  },
  {
    id: "p_y2k_4",
    title: "Washed Crop Hoodie — Baby Pink",
    description: "Acid-washed cropped hoodie with kangaroo pocket in baby pink.",
    category: "fashion",
    images: ["https://images.unsplash.com/photo-1571513800374-df1bbe650e56?w=600&q=80"],
    price: 1199, mrp: 2200, currency: "INR",
    seller: MOCK_SELLER_BRAND, rating: 4.5, review_count: 1432,
    aesthetic_codes: ["y2k"],
    similarity_score: 88, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 90, color: 92, material: 84, style: 88, overall: 88 },
    original_ref: { name: "Vintage Crop Hoodie", brand: "Brandy Melville", price: 4200 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Same washed-out Y2K hoodie. 71% cheaper.",
      what_matches: ["Acid-wash fade effect", "Cropped boxy fit", "Kangaroo pocket"],
      what_differs: ["350gsm vs 400gsm fleece — slightly lighter"],
      ai_recommendation: "Same vibe. Great for the price. Save ₹3,000.",
    },
    material_details: ["80% Cotton, 20% Polyester fleece", "Acid wash treatment", "Ribbed cuffs and hem"],
    care_instructions: ["Machine wash inside out cold", "Tumble dry low"],
    ships_in_days: "2-3 business days",
    variants: [
      { id: "v-xs", size: "XS", price: 1199, mrp: 2200, stock_count: 7 },
      { id: "v-s",  size: "S",  price: 1199, mrp: 2200, stock_count: 10 },
      { id: "v-m",  size: "M",  price: 1199, mrp: 2200, stock_count: 8 },
      { id: "v-l",  size: "L",  price: 1199, mrp: 2200, stock_count: 4 },
    ],
  },
  {
    id: "p_y2k_5",
    title: "Butterfly Hair Clips Set (12 pcs)",
    description: "Y2K-era iridescent butterfly clips — 12 assorted sizes.",
    category: "beauty",
    images: ["https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=600&q=80"],
    price: 349, mrp: 700, currency: "INR",
    seller: MOCK_SELLER_BRAND, rating: 4.3, review_count: 3421,
    aesthetic_codes: ["y2k"],
    similarity_score: 90, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 92, color: 91, material: 88, style: 90, overall: 90 },
    original_ref: { name: "Y2K Butterfly Clips (6 pcs)", brand: "Kitsch", price: 1800 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "12 clips for less than 6 of the originals. 81% cheaper.",
      what_matches: ["Same butterfly wing shape", "Iridescent finish", "Snap closure mechanism"],
      what_differs: ["Slightly lighter plastic — but 12pcs vs 6pcs"],
      ai_recommendation: "You're getting 2x the clips for 1/5 the price. Buy this.",
    },
    material_details: ["ABS plastic with iridescent coating", "Snap-click closure", "Assorted sizes"],
    care_instructions: ["Wipe clean"],
    ships_in_days: "1-2 business days",
  },

  // ── Japandi ───────────────────────────────────────────────────────────────
  {
    id: "p_jp_1",
    title: "Handwoven Rattan Serving Tray",
    description: "Oval rattan tray with natural handles — ideal for the japandi home.",
    category: "home",
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80"],
    price: 799, mrp: 1500, currency: "INR",
    seller: MOCK_SELLER_ARTISAN, rating: 4.7, review_count: 634,
    aesthetic_codes: ["japandi"],
    similarity_score: 92, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 94, color: 95, material: 90, style: 92, overall: 92 },
    original_ref: { name: "Rattan Serving Tray", brand: "Pottery Barn", price: 4500 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Same woven rattan craft. 82% cheaper.",
      what_matches: ["Identical weave pattern", "Same natural tan colour", "Oval form with handles"],
      what_differs: ["Handles slightly thicker — actually more durable"],
      ai_recommendation: "Made by Jaipur artisans with the same technique. Save ₹3,700.",
    },
    material_details: ["Natural rattan core", "Hand-woven by artisans", "Food-safe lacquer finish"],
    care_instructions: ["Wipe with damp cloth", "Dry immediately", "Avoid prolonged moisture"],
    ships_in_days: "3-4 business days",
  },
  {
    id: "p_jp_2",
    title: "Terracotta Incense Holder — Minimal",
    description: "Unglazed terracotta incense holder, wabi-sabi aesthetic.",
    category: "home",
    images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80"],
    price: 499, mrp: 900, currency: "INR",
    seller: MOCK_SELLER_LOCAL, rating: 4.6, review_count: 892,
    aesthetic_codes: ["japandi"],
    similarity_score: 89, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 91, color: 90, material: 88, style: 89, overall: 89 },
    original_ref: { name: "Ceramic Incense Holder", brand: "Maison Margiela Home", price: 3200 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Wabi-sabi aesthetic. 84% cheaper.",
      what_matches: ["Unglazed matte finish", "Simple channel groove", "Understated form"],
      what_differs: ["Terracotta vs glazed ceramic"],
      ai_recommendation: "The unglazed finish is actually more authentic to wabi-sabi. Save ₹2,700.",
    },
    material_details: ["Unglazed terracotta", "Handthrown on potter's wheel", "Fits standard agarbatti"],
    care_instructions: ["Wipe ash when cool", "Do not immerse in water"],
    ships_in_days: "3-5 business days",
  },
  {
    id: "p_jp_3",
    title: "Pre-washed Linen Throw Blanket — Stone Grey",
    description: "Stonewashed linen-cotton throw with natural fringed edges.",
    category: "home",
    images: ["https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=600&q=80"],
    price: 2199, mrp: 4000, currency: "INR",
    seller: MOCK_SELLER_D2C, rating: 4.8, review_count: 421,
    aesthetic_codes: ["japandi"],
    similarity_score: 90, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 91, color: 93, material: 88, style: 90, overall: 90 },
    original_ref: { name: "Linen Throw Blanket", brand: "H&M Home Premium", price: 6500 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Pre-washed linen at 66% off premium retail.",
      what_matches: ["Pre-washed stonewash finish", "Same 130x170cm dimensions", "Fringe edge detail"],
      what_differs: ["Linen-cotton blend vs pure linen"],
      ai_recommendation: "The blend actually washes better. Save ₹4,300.",
    },
    material_details: ["60% Linen, 40% Cotton", "Pre-washed for softness", "Naturally fringed edges"],
    care_instructions: ["Machine wash cold", "Tumble dry low", "Remove promptly to reduce wrinkles"],
    ships_in_days: "3-4 business days",
  },
  {
    id: "p_jp_4",
    title: "Bamboo Desktop Organiser — 3-slot",
    description: "Natural moso bamboo desktop organiser with clean modular design.",
    category: "home",
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80"],
    price: 649, mrp: 1200, currency: "INR",
    seller: MOCK_SELLER_BRAND, rating: 4.5, review_count: 1203,
    aesthetic_codes: ["japandi"],
    similarity_score: 88, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 90, color: 88, material: 87, style: 88, overall: 88 },
    original_ref: { name: "Bamboo Desk Organiser", brand: "Muji", price: 2800 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "Same Muji-style minimalism. 77% cheaper.",
      what_matches: ["Natural bamboo material", "Clean modular design", "Same slot dimensions"],
      what_differs: ["Bamboo grain slightly more visible — more natural character"],
      ai_recommendation: "Functionally identical. Save ₹2,150.",
    },
    material_details: ["Moso bamboo", "Water-based sealant", "Non-slip base pads"],
    care_instructions: ["Wipe clean", "Keep dry", "Occasional conditioning oil recommended"],
    ships_in_days: "2-3 business days",
  },
  {
    id: "p_jp_5",
    title: "Japanese Washi Tape Set (12 rolls)",
    description: "Assorted washi tape set with 12 rolls in muted japandi tones.",
    category: "home",
    images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80"],
    price: 399, mrp: 750, currency: "INR",
    seller: MOCK_SELLER_BRAND, rating: 4.6, review_count: 2108,
    aesthetic_codes: ["japandi"],
    similarity_score: 87, similarity_tier: "smart_value",
    similarity_breakdown: { shape: 88, color: 90, material: 84, style: 88, overall: 87 },
    original_ref: { name: "MT Washi Tape Set (8 rolls)", brand: "MT Casa Japan", price: 2200 },
    ai_explanation: {
      verdict: "excellent_value",
      headline: "12 rolls for less than 8 MT brand rolls. 82% cheaper.",
      what_matches: ["Rice paper base material", "Same 15mm width", "Repositionable adhesive"],
      what_differs: ["Paper weight slightly lighter", "Colours less saturated than MT brand"],
      ai_recommendation: "For journaling and home decoration, excellent value. Save ₹1,800.",
    },
    material_details: ["Washi rice paper base", "Repositionable adhesive", "15mm width, 10m per roll"],
    care_instructions: ["Store away from heat and direct sunlight"],
    ships_in_days: "1-2 business days",
  },
];

// ─── O(1) product lookup (defined AFTER all products) ────────────────────────

export const MOCK_PRODUCTS_BY_ID: Record<string, Product> = {
  ...Object.fromEntries(MOCK_PRODUCTS.map((p) => [p.id, p])),
  [MOCK_PRODUCT_DETAIL.id]: MOCK_PRODUCT_DETAIL,
};

// ─── Legacy recommendation cards ─────────────────────────────────────────────

export const MOCK_RECOMMENDATIONS: Product[] = [
  {
    id: "p1", title: "Minimal Ceramic Vase — Matte White", category: "home",
    images: ["https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=400&q=80"],
    price: 890, mrp: 1200, currency: "INR", seller: MOCK_SELLER_ARTISAN,
    rating: 4.8, review_count: 342,
    aesthetic_codes: ["japandi"],
    original_ref: { name: "Matte Ceramic Vase", brand: "Zara Home", price: 2500 },
  },
  {
    id: "p2", title: "Linen Tote Bag — Natural", category: "fashion",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80"],
    price: 1200, mrp: 1800, currency: "INR", seller: MOCK_SELLER_ARTISAN,
    rating: 4.6, review_count: 218,
    aesthetic_codes: ["quiet_luxury"],
    original_ref: { name: "Canvas Tote", brand: "The Row", price: 15000 },
  },
  {
    id: "p3", title: "Rattan Side Table — Handwoven", category: "furniture",
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80"],
    price: 3200, mrp: 5000, currency: "INR", seller: MOCK_SELLER_ARTISAN,
    rating: 4.5, review_count: 87,
    aesthetic_codes: ["japandi"],
    original_ref: { name: "Rattan Side Table", brand: "West Elm", price: 24999 },
  },
  {
    id: "p4", title: "Cotton Kurta — Block Print", category: "fashion",
    images: ["https://images.unsplash.com/photo-1605289982774-9a6fef564df8?w=400&q=80"],
    price: 1650, mrp: 2500, currency: "INR", seller: MOCK_SELLER_BRAND,
    rating: 4.4, review_count: 530,
    aesthetic_codes: ["artisan_craft"],
    original_ref: { name: "Block Print Kurta", brand: "Fabindia", price: 3200 },
  },
];

export const MOCK_SEARCH_RESULT: VisualSearchResult = {
  search_id: "sr_mock_001",
  query_image_url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
  identified_product: {
    name: "Rattan Side Table",
    category: "furniture",
    estimated_price: 25000,
    source_platform: "instagram",
    detected_attributes: {
      material: "rattan / natural fibre",
      style: "coastal / japandi",
      color: "natural tan",
      shape: "round",
    },
  },
  results: {
    original: [
      {
        id: "o1", title: "West Elm x Pottery Barn Rattan Side Table",
        category: "furniture",
        images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80"],
        price: 24999, mrp: 29999, currency: "INR",
        seller: { id: "s_we", name: "West Elm India", type: "brand", is_verified: true, is_local: false, rating: 4.3 },
        rating: 4.3, review_count: 212,
        similarity_score: 97, similarity_tier: "original",
        similarity_breakdown: { shape: 97, color: 98, material: 94, style: 96, overall: 97 },
        ai_explanation: {
          verdict: "excellent_value",
          headline: "This is the original — or very close to it.",
          what_matches: ["Identical woven rattan weave pattern", "Same round form factor", "Same natural tan colour"],
          what_differs: ["Premium brand price", "West Elm label on the base"],
          ai_recommendation: "This IS the product. Buy if budget allows.",
        },
      },
    ],
    smart_value: [
      {
        id: "sv1", title: "Handwoven Rattan Side Table — Rajwada Crafts",
        category: "furniture",
        images: ["https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80"],
        price: 3200, mrp: 5000, currency: "INR",
        seller: MOCK_SELLER_ARTISAN,
        rating: 4.7, review_count: 87,
        similarity_score: 91, similarity_tier: "smart_value",
        similarity_breakdown: { shape: 94, color: 96, material: 89, style: 88, overall: 91 },
        ai_explanation: {
          verdict: "excellent_value",
          headline: "87% cheaper. You'll barely notice the difference.",
          what_matches: ["Same rattan weave technique", "Same round silhouette", "Same natural color tone"],
          what_differs: ["Slightly thicker weave — actually more durable", "No brand name", "Hand-finished vs. factory finish"],
          ai_recommendation: "Best value pick. Made by a Jaipur artisan family. Buy this.",
        },
      },
      {
        id: "sv2", title: "Nilkamal Rattan-Style Side Table",
        category: "furniture",
        images: ["https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=400&q=80"],
        price: 4999, mrp: 7500, currency: "INR",
        seller: MOCK_SELLER_BRAND,
        rating: 4.0, review_count: 1240,
        similarity_score: 84, similarity_tier: "smart_value",
        similarity_breakdown: { shape: 88, color: 90, material: 75, style: 80, overall: 84 },
        ai_explanation: {
          verdict: "good_match",
          headline: "Looks very similar. Material is different.",
          what_matches: ["Round form and proportions match well", "Natural-looking colour", "Similar height and surface size"],
          what_differs: ["Synthetic rattan — not real natural fibre", "Slightly different weave pattern"],
          ai_recommendation: "Good for high-traffic use — more durable. Aesthetic is 84% there.",
        },
      },
    ],
    similar: [
      {
        id: "si1", title: "Wooden Stool with Wicker Top",
        category: "furniture",
        images: ["https://images.unsplash.com/photo-1567538096621-38d2284b23ff?w=400&q=80"],
        price: 1899, mrp: 2800, currency: "INR",
        seller: { id: "s_ws", name: "Wooden Street", type: "brand", is_verified: true, is_local: false, rating: 4.1 },
        rating: 4.1, review_count: 445,
        similarity_score: 74, similarity_tier: "similar",
        similarity_breakdown: { shape: 72, color: 80, material: 70, style: 72, overall: 74 },
      },
    ],
  },
  total_results: 4,
  search_time_ms: 1240,
};

export const MOCK_REVIEWS: ReviewsData = {
  average: 4.6,
  total: 847,
  distribution: [
    { stars: 5, count: 612 }, { stars: 4, count: 157 },
    { stars: 3, count: 52 },  { stars: 2, count: 18 },
    { stars: 1, count: 8 },
  ],
  ai_summary: {
    praise_themes: ["Quality linen feel", "True to images", "Good finish", "Great value"],
    concern_themes: ["Sizing runs large (order one size down)", "Slight colour variation in photos"],
    size_guidance: "Runs 1 size large — most buyers recommend ordering 1 size down from your usual.",
  },
  samples: [
    {
      id: "r1", author: "Priya M.", rating: 5, is_verified_purchase: true,
      title: "Looks way more expensive than ₹2,499",
      body: "Genuinely shocked at the quality. The linen is thick and hangs beautifully. Zero regrets.",
      created_at: "Jul 2026",
    },
    {
      id: "r2", author: "Ananya K.", rating: 4, is_verified_purchase: true,
      title: "Lovely but size up issue",
      body: "The fabric and stitching are great. Ordered M and it was quite loose — should have gone S.",
      created_at: "Jun 2026",
    },
    {
      id: "r3", author: "Rohini S.", rating: 5, is_verified_purchase: true,
      title: "Exactly what I needed for summer",
      body: "Light, breathable, and looks so clean. The sage green colour in person is even better than the photos.",
      created_at: "Jun 2026",
    },
  ],
};
