import { FormEvent, useEffect, useState } from "react";
import { CreatorProfile, CreatorProfileInput, getCreatorApplications, getCreatorProfile, getMediaKit, saveCreatorProfile } from "./api";

type Props = { page: "onboarding" | "profile" | "media-kit" | "applications"; navigate: (path: string) => void };
const empty: CreatorProfileInput = { displayName: "", handle: "", bio: "", city: "", state: "", travelAvailability: false, languages: [], niches: [], contentFormats: [], socialChannels: [], audienceDemographics: "", topCities: [], interests: [], services: [], portfolioLinks: [], campaignPreferences: { preferredPlatforms: [], minimumRate: 0, acceptsBarter: false, availability: "available" } };
const list = (value: string) => value.split(",").map((x) => x.trim()).filter(Boolean);
const join = (value?: string[]) => (value ?? []).join(", ");
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="creator-field">{label}{children}</label>; }

export default function CreatorProfileApp({ page, navigate }: Props) {
  if (page === "onboarding") return <Wizard navigate={navigate} />;
  if (page === "profile") return <Profile navigate={navigate} />;
  if (page === "media-kit") return <MediaKit navigate={navigate} />;
  return <Applications navigate={navigate} />;
}
function Wizard({ navigate }: Pick<Props, "navigate">) {
  const [form, setForm] = useState<CreatorProfileInput>(empty), [step, setStep] = useState(0), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { const local = localStorage.getItem("ck-creator-draft"); if (local) setForm(JSON.parse(local)); getCreatorProfile().then(({ profile }) => profile && setForm(profile)).catch(() => undefined); }, []);
  const update = (data: Partial<CreatorProfileInput>) => setForm((old) => ({ ...old, ...data }));
  const save = async (submit = false) => { setSaving(true); setError(""); try { const result = await saveCreatorProfile(form, submit); localStorage.removeItem("ck-creator-draft"); if (submit) navigate("/creator/profile"); else setForm(result.profile); } catch (e) { setError(e instanceof Error ? e.message : "Could not save your profile."); } finally { setSaving(false); } };
  const next = () => {
    const invalid = (step === 0 && (!form.displayName?.trim() || !form.handle?.trim() || !form.bio?.trim() || !form.city?.trim() || !form.state?.trim()))
      || (step === 1 && (!(form.languages?.length) || !(form.niches?.length) || !(form.contentFormats?.length)))
      || (step === 2 && !(form.socialChannels?.length))
      || (step === 4 && !(form.services?.length))
      || (step === 5 && !(form.campaignPreferences?.preferredPlatforms.length));
    if (invalid) { setError("Complete the required fields in this step before continuing."); return; }
    if (step === 6) { void save(true); return; }
    localStorage.setItem("ck-creator-draft", JSON.stringify(form)); void save(false); setStep(step + 1);
  };
  const text = (key: "displayName" | "handle" | "bio" | "city" | "state" | "audienceDemographics") => <input value={form[key] ?? ""} onChange={(e) => update({ [key]: e.target.value })} />;
  const listField = (key: "languages" | "niches" | "contentFormats" | "topCities" | "interests" | "portfolioLinks", label: string) => <Field label={label}><input value={join(form[key])} onChange={(e) => update({ [key]: list(e.target.value) })} placeholder="Separate with commas" /></Field>;
  const views = [
    <><h1>Put your work in context.</h1><Field label="Display name">{text("displayName")}</Field><Field label="Handle">{text("handle")}</Field><Field label="Short bio">{text("bio")}</Field><Field label="City">{text("city")}</Field><Field label="State">{text("state")}</Field><label className="check"><input type="checkbox" checked={!!form.travelAvailability} onChange={(e) => update({ travelAvailability: e.target.checked })} /> Available to travel for campaigns</label></>,
    <><h1>Your creative focus.</h1>{listField("languages", "Languages")}{listField("niches", "Niches")}{listField("contentFormats", "Content formats")}</>,
    <><h1>Show your channels.</h1><p>Metrics are clearly labelled self-reported until reviewed.</p>{(form.socialChannels ?? []).map((c, i) => <div className="channel-form" key={i}><select value={c.platform} aria-label={`Channel ${i + 1} platform`} onChange={(e) => update({ socialChannels: form.socialChannels?.map((v, n) => n === i ? { ...v, platform: e.target.value } : v) })}><option>Instagram</option><option>YouTube</option><option>TikTok</option><option>LinkedIn</option></select><input value={c.handle} aria-label={`Channel ${i + 1} handle`} placeholder="@handle" onChange={(e) => update({ socialChannels: form.socialChannels?.map((v, n) => n === i ? { ...v, handle: e.target.value } : v) })}/><input value={c.url} aria-label={`Channel ${i + 1} URL`} placeholder="https://..." onChange={(e) => update({ socialChannels: form.socialChannels?.map((v, n) => n === i ? { ...v, url: e.target.value } : v) })}/><input type="number" value={c.followers} aria-label={`Channel ${i + 1} followers`} placeholder="Followers" onChange={(e) => update({ socialChannels: form.socialChannels?.map((v, n) => n === i ? { ...v, followers: Number(e.target.value) } : v) })}/><input type="number" value={c.avgViews} aria-label={`Channel ${i + 1} average views`} placeholder="Average views" onChange={(e) => update({ socialChannels: form.socialChannels?.map((v, n) => n === i ? { ...v, avgViews: Number(e.target.value) } : v) })}/><input type="number" value={c.engagementRate} aria-label={`Channel ${i + 1} engagement rate`} placeholder="Engagement rate %" onChange={(e) => update({ socialChannels: form.socialChannels?.map((v, n) => n === i ? { ...v, engagementRate: Number(e.target.value) } : v) })}/></div>)}<button type="button" className="creator-secondary" onClick={() => update({ socialChannels: [...(form.socialChannels ?? []), { platform: "Instagram", handle: "", url: "", followers: 0, avgViews: 0, engagementRate: 0, verificationStatus: "self-reported" }] })}>Add channel</button></>,
    <><h1>Know your audience.</h1><Field label="Audience demographics">{text("audienceDemographics")}</Field>{listField("topCities", "Top cities")}{listField("interests", "Audience interests")}</>,
    <><h1>Services and proof.</h1>{(form.services ?? []).map((s, i) => <div className="channel-form" key={i}><input value={s.service} aria-label={`Service ${i + 1} name`} placeholder="Service" onChange={(e) => update({ services: form.services?.map((v, n) => n === i ? { ...v, service: e.target.value } : v) })}/><input type="number" value={s.rate} aria-label={`Service ${i + 1} rate`} placeholder="Rate" onChange={(e) => update({ services: form.services?.map((v, n) => n === i ? { ...v, rate: Number(e.target.value) } : v) })}/></div>)}<button type="button" className="creator-secondary" onClick={() => update({ services: [...(form.services ?? []), { service: "", rate: 0 }] })}>Add service</button>{listField("portfolioLinks", "Portfolio links")}</>,
    <><h1>Choose the right briefs.</h1><Field label="Preferred platforms"><input value={join(form.campaignPreferences?.preferredPlatforms)} onChange={(e) => update({ campaignPreferences: { ...form.campaignPreferences!, preferredPlatforms: list(e.target.value) } })} /></Field><Field label="Minimum rate"><input type="number" value={form.campaignPreferences?.minimumRate ?? 0} onChange={(e) => update({ campaignPreferences: { ...form.campaignPreferences!, minimumRate: Number(e.target.value) } })} /></Field><label className="check"><input type="checkbox" checked={!!form.campaignPreferences?.acceptsBarter} onChange={(e) => update({ campaignPreferences: { ...form.campaignPreferences!, acceptsBarter: e.target.checked } })}/> Open to barter</label><Field label="Availability"><select value={form.campaignPreferences?.availability} onChange={(e) => update({ campaignPreferences: { ...form.campaignPreferences!, availability: e.target.value as "available" } })}><option value="available">Available</option><option value="limited">Limited</option><option value="unavailable">Unavailable</option></select></Field></>,
    <><h1>Review before you go live.</h1><p><strong>{form.displayName || "Your name"}</strong> {form.handle} · {join(form.niches)}</p><p>{(form.socialChannels ?? []).length} channel(s), {(form.services ?? []).length} service(s), and preferences ready to share.</p><p>Your public media kit will never include campaign preferences.</p></>
  ];
  return <main className="creator-page"><div className="creator-progress" aria-label={`Step ${step + 1} of 7`}><span style={{ width: `${((step + 1) / 7) * 100}%` }} /></div><div className="creator-wizard"><small>Creator onboarding · Step {step + 1} of 7</small>{views[step]}{error && <p className="form-error" role="alert">{error}</p>}<footer><button className="creator-secondary" disabled={!step || saving} onClick={() => setStep(step - 1)}>Back</button><button className="creator-primary" disabled={saving} onClick={next}>{saving ? "Saving…" : step === 6 ? "Complete profile" : "Continue"}</button></footer></div></main>;
}
function Profile({ navigate }: Pick<Props, "navigate">) { const [profile, setProfile] = useState<CreatorProfile | null>(null); useEffect(() => { getCreatorProfile().then((x) => setProfile(x.profile)).catch(() => undefined); }, []); if (!profile) return <main className="creator-page"><div className="creator-wizard"><h1>Your creator profile</h1><p>Build a profile so relevant campaigns can find you.</p><button className="creator-primary" onClick={() => navigate("/onboarding/creator")}>Start onboarding</button></div></main>; return <main className="creator-page"><section className="creator-overview"><div><small>Creator profile</small><h1>{profile.displayName}</h1><p>{profile.handle} · {profile.city}, {profile.state}</p><p>{profile.bio}</p></div><div className="completion"><strong>{profile.completionPercentage}%</strong><span>complete</span></div></section><div className="creator-actions"><button className="creator-primary" onClick={() => navigate("/onboarding/creator")}>Edit profile</button><button className="creator-secondary" onClick={() => navigate("/creator/media-kit")}>View media kit</button><button className="creator-secondary" onClick={() => navigate("/creator/applications")}>Applications</button></div><section className="creator-grid"><article><h2>Creative focus</h2><p>{join(profile.niches)} · {join(profile.contentFormats)}</p><h2>Channels</h2>{profile.socialChannels.map((c) => <p key={c.url}><strong>{c.platform}</strong> {c.handle} · {c.followers.toLocaleString()} followers <small>Self-reported</small></p>)}</article><article><h2>Services</h2>{profile.services.map((s) => <p key={s.service}>{s.service} <strong>₹{s.rate.toLocaleString("en-IN")}</strong></p>)}<h2>Verification</h2><p>{profile.verificationStatus}</p></article></section></main>; }
function MediaKit({ navigate }: Pick<Props, "navigate">) { const [profile, setProfile] = useState<Omit<CreatorProfile, "campaignPreferences" | "verificationStatus" | "completed"> | null>(null); const [state, setState] = useState<"loading" | "empty" | "incomplete" | "not-found" | "error">("loading"); const [error, setError] = useState(""); useEffect(() => { getCreatorProfile().then(({ profile: p }) => { if (!p) { setState("empty"); return; } if (!p.completed) { setState("incomplete"); return; } getMediaKit(p.handle).then((x) => { setProfile(x.profile); setState("loading"); }).catch((e: Error) => { setError(e.message); setState(/not found/i.test(e.message) ? "not-found" : "error"); }); }).catch((e: Error) => { setError(e.message); setState("error"); }); }, []); const message = state === "loading" ? "Loading your public media kit…" : state === "empty" ? "Create a creator profile to preview your media kit." : state === "incomplete" ? "Complete your profile before publishing a media kit." : state === "not-found" ? "Your public media kit is not available yet." : error; return <main className="creator-page">{profile ? <section className="media-kit"><small>CollabKaro creator media kit</small><h1>{profile.displayName}</h1><p>{profile.handle} · {profile.city}, {profile.state}</p><p>{profile.bio}</p><h2>Creative world</h2><p>{join(profile.niches)} · {join(profile.contentFormats)}</p><h2>Channels</h2>{profile.socialChannels.map((c) => <p key={c.url}>{c.platform} · {c.followers.toLocaleString()} followers · Self-reported</p>)}<h2>Portfolio</h2>{profile.portfolioLinks.map((link) => <a key={link} href={link} target="_blank" rel="noreferrer">{link}</a>)}</section> : <section className="media-kit"><p role={state === "error" ? "alert" : undefined}>{message}</p>{(state === "empty" || state === "incomplete") && <button className="creator-primary" onClick={() => navigate("/onboarding/creator")}>Complete your profile</button>}</section>}<button className="creator-secondary" onClick={() => navigate("/creator/profile")}>Back to profile</button></main>; }
function Applications({ navigate }: Pick<Props, "navigate">) { const [items, setItems] = useState<Awaited<ReturnType<typeof getCreatorApplications>>["applications"]>([]), [error, setError] = useState(""), [loading, setLoading] = useState(true); useEffect(() => { getCreatorApplications().then((x) => setItems(x.applications)).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); }, []); return <main className="creator-page"><h1>Your applications</h1>{loading && <p>Loading applications…</p>}{error && <p role="alert">{error}</p>}{!loading && !error && !items.length && <p>No applications yet. Find a brief that feels like you.</p>}{items.map((item) => <article className="application-card" key={item.id}><small>{item.status}</small><h2>{item.campaign?.title ?? "Campaign unavailable"}</h2><p>{item.campaign?.brand} · ₹{item.proposedRate.toLocaleString("en-IN")}</p><time>{new Date(item.createdAt).toLocaleDateString("en-IN")}</time></article>)}<button className="creator-secondary" onClick={() => navigate("/")}>Discover campaigns</button></main>; }