const fs = require('fs');
const path = require('path');

const data = {
  "16": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAbklEQVR4nGOw2PvjPyWYAZugwM5GFEyUAfziWhga0TFIDQxjGEBIM7oheA34Yh8HxkQbgE0zCMMUYzOEJAPQDcFrAHpgUcUAgl7AZwhZsUBWNBKTkPB6gZCf0cXxGoAPoxuCNTMRwsiGkGUAsiEA8PVZ4xg1BQsAAAAASUVORK5CYII=",
  "48": "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAABFElEQVR4nO3ZsRHCMBAEQHcAGT1QARmd0AtlEdAVARlEnoFA1t//vf80dnDp69aWNJ7xdHm+PyNnqi6wA6oL0AGH0xnK8XE3BZ3bCg1gLc7GhAGR4gyEG8AqHoW4AFnlPQgYkF0eRUCAtcojiO0A1i5vRVABr+vtL78FshAmgKf8HMYtlg5olWchQoDI018CsBClAARRBujdIhIA9BB7EKmAeRhaXA7gTTkgihgaIHOIhwd4EIzZtG8hD0ISYEEw56UAWguz5sCAyOLR9N6mGVCF2AGsfZyFgAFqCBdACeEGVEHoAAYCnUUHeDGRGWkAVqwIWYAVIQ3wIOQAKEISgCBkAVaE/I/u4QE9xBCAJcQwgBbiC1aahkh2UdpTAAAAAElFTkSuQmCC",
  "128": "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAC4UlEQVR4nO3TsUEdUQxEUTowGT24AjI6cS+UReCuHJDZKYGDv+yTZka6wc1Xb84+vf7+/Et7e1J/AAGAAEAAIAAQAAgABADyAvDj5ScFtg7A88f7Q6m/EwCNY19JfRMAmgefDiIegGL0SRBiAagHn4IhDoB63GkQYgCox5wKwR6AerzpCKwBqEfbAMEWgHqoLQjsAKjH2YbACoB6lI0QbACoh9iKwAKAegCH1gJQP7xT6wCoH9yxNQDUD+3aCgDqR3YPADQXgPphkxoHQP2gaY0CoH7M1ABA+QDUD5geAB7sz9uv/6Ye0BlBOQDl8JMgAODG8F979GHUg3chKAXgNv53IDhhAMCh8a8CcIIQA8D577+DQA1hPYBT44MAALcAKBHYA0gZ/y4AFQIAGAFIRwCAQw8JgOUAuhHYAqg8GgAAsAaQiCAKQAUCACwGcHr8bgQrAZxEAIDDADoPdx0fAAEAKscHQPPhbuN3IgDABQRdwwMg5HAAAAAAAAAAAAAAAAAAIG58SwBpxwMAAAAAAAAiAbgiSLsfAKEATn1vNAA3BIl3HweQ+hBJ4wPAEEHqzSMAqBEk3zoGgApB+p0lALYgmHDjOABdCKbcVgZgKgLlTQAQP5j6FgCIHk797VXjlwNwerwrj6n+NgBQy/gtAEAAAPnjpVc1fhsAEAAABIbjA8C86vhbAEAAoHMIABAcAAgAdA4BAIYEAAM4f1+x0d/v36l7+g+f4oH730iAAA="
};

const iconsDir = path.join(__dirname, '..', 'dupescout', 'extension', 'icons');
if (!fs.existsSync(iconsDir)) {
  fs.mkdirSync(iconsDir, { recursive: true });
}

for (const [size, b64] of Object.entries(data)) {
  const buf = Buffer.from(b64, 'base64');
  const filePath = path.join(iconsDir, `icon-${size}.png`);
  fs.writeFileSync(filePath, buf);
  console.log(`Saved ${filePath} (${buf.length} bytes)`);
}
