import React, { useState, useEffect } from 'react';
import { PROMPT_CATEGORIES, PROMPT_TEMPLATES, interpolatePrompt } from '../data/promptVaultData';
import { 
  Sparkles, Copy, Check, Terminal, Code2, Search, Sliders, 
  ExternalLink, Layers, ShieldCheck, Rocket, BookOpen, Filter, CheckCircle2,
  Download, FileText, ArrowRight, PlayCircle
} from 'lucide-react';
import { downloadMarkdownFile } from '../utils/zipExport';

export default function PromptVaultStudio({ 
  ideas = [], 
  activeIdea, 
  setActiveIdea,
  initialCategory = 'all',
  configuredStack = null 
}) {
  // Category filter state: 'all' | 'autonomous-pipeline' | 'prd' | 'architecture' | 'agent-coding' | 'security-qa' | 'gtm-branding'
  const [selectedCategory, setSelectedCategory] = useState(initialCategory || 'all');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedPromptId, setSelectedPromptId] = useState(
    initialCategory === 'autonomous-pipeline' ? 'auto-01-scaffold' : PROMPT_TEMPLATES[0].id
  );

  // Active workspace interpolation context
  const [selectedIdeaId, setSelectedIdeaId] = useState(activeIdea ? activeIdea.id : (ideas[0]?.id || 'custom'));
  
  // Custom context overrides
  const currentIdea = ideas.find(i => i.id === selectedIdeaId) || activeIdea;
  const [customContext, setCustomContext] = useState({
    PRODUCT_NAME: currentIdea?.name || 'StartupOS',
    TARGET_AUDIENCE: currentIdea?.audience || 'Solo Builders, PMs & Student Developers',
    CORE_PROBLEM: currentIdea?.problem || '0-to-1 building friction, architecture sprawl & lack of governance',
    CORE_ADVANTAGE: currentIdea?.advantage || 'Universal Launchpad, 4-File Parity & LMS Hub',
    TECH_STACK: configuredStack || 'React 18 + Vite + Node.js Express + SQLite / PostgreSQL'
  });

  const [copiedKey, setCopiedKey] = useState(null);

  useEffect(() => {
    if (initialCategory) {
      setSelectedCategory(initialCategory);
      if (initialCategory === 'autonomous-pipeline') {
        setSelectedPromptId('auto-01-scaffold');
      }
    }
  }, [initialCategory]);

  useEffect(() => {
    if (configuredStack) {
      setCustomContext(prev => ({ ...prev, TECH_STACK: configuredStack }));
    }
  }, [configuredStack]);

  useEffect(() => {
    if (activeIdea) {
      setSelectedIdeaId(activeIdea.id);
      setCustomContext(prev => ({
        ...prev,
        PRODUCT_NAME: activeIdea.name,
        TARGET_AUDIENCE: activeIdea.audience,
        CORE_PROBLEM: activeIdea.problem,
        CORE_ADVANTAGE: activeIdea.advantage || prev.CORE_ADVANTAGE
      }));
    }
  }, [activeIdea]);

  // Sync when user picks a different idea from workspace
  const handleIdeaSelect = (ideaId) => {
    setSelectedIdeaId(ideaId);
    const idea = ideas.find(i => i.id === ideaId);
    if (idea) {
      setCustomContext({
        PRODUCT_NAME: idea.name,
        TARGET_AUDIENCE: idea.audience,
        CORE_PROBLEM: idea.problem,
        CORE_ADVANTAGE: idea.advantage || 'AI-native streamlined execution',
        TECH_STACK: configuredStack || 'React 18 + Vite + Node Express + SQLite'
      });
      if (setActiveIdea) setActiveIdea(idea);
    }
  };

  const pipelinePrompts = PROMPT_TEMPLATES.filter(p => p.category === 'autonomous-pipeline');
  const fullPipelineMarkdown = `# 🚀 Autonomous 0-to-1 Build Pipeline for ${customContext.PRODUCT_NAME}

> Generated by StartupOS Prompt Vault. Run each phase sequentially with your AI assistant (AntiGravity, Claude Code, or Cursor).

---

${pipelinePrompts.map(p => `## ${p.title} (${p.badge})\n\n${interpolatePrompt(p.template, customContext)}\n\n---\n`).join('\n')}`;

  const handleDownloadFullPipeline = () => {
    downloadMarkdownFile(`${(customContext.PRODUCT_NAME || 'project').toLowerCase().replace(/[^a-z0-9]+/g, '-')}-build-pipeline.md`, fullPipelineMarkdown);
  };

  // Filter templates
  const filteredPrompts = PROMPT_TEMPLATES.filter(p => {
    const matchesCategory = selectedCategory === 'all' || p.category === selectedCategory;
    const matchesSearch = searchQuery === '' || 
      p.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.tags.some(t => t.toLowerCase().includes(searchQuery.toLowerCase()));
    return matchesCategory && matchesSearch;
  });

  const activePrompt = PROMPT_TEMPLATES.find(p => p.id === selectedPromptId) || filteredPrompts[0] || PROMPT_TEMPLATES[0];
  const renderedPromptText = interpolatePrompt(activePrompt.template, customContext);

  const handleCopy = (key, text) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  // Estimate tokens (approx 4 chars per token)
  const estimatedTokens = Math.round(renderedPromptText.length / 4);

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 space-y-8">
      {/* Header Banner */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-slate-900 via-purple-950 to-slate-900 p-8 border border-slate-800 text-white shadow-xl">
        <div className="absolute top-0 right-0 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl pointer-events-none -mr-20 -mt-20"></div>
        <div className="relative z-10 max-w-3xl space-y-3">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/20 border border-purple-400/30 text-purple-300 text-xs font-semibold uppercase tracking-wider">
            <Sparkles className="w-3.5 h-3.5" />
            Phase 2 • What Prompts to Give
          </div>
          <h1 className="text-3xl sm:text-4xl font-black tracking-tight text-white">
            Battle-Tested AI Prompt Vault & Spec Studio
          </h1>
          <p className="text-slate-300 text-sm sm:text-base leading-relaxed">
            Stop guessing prompts. Access the exact, high-converting prompt engineering suites used by top AI PMs and 0-to-1 founders. 
            Prompts dynamically populate with your active project workspace variables for instant copying to AntiGravity, Claude Code, or Cursor.
          </p>
        </div>
      </div>

      {/* Workspace Context Injector Bar */}
      <div className="bg-white border border-slate-200/90 rounded-2xl p-5 shadow-sm space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2">
            <Sliders className="w-4 h-4 text-purple-600" />
            <h2 className="text-sm font-bold text-slate-900">
              Live Workspace Variable Injector
            </h2>
            <span className="text-[10px] bg-purple-50 text-purple-700 font-bold px-2 py-0.5 rounded-full border border-purple-200">
              Auto-Interpolated
            </span>
          </div>

          {ideas.length > 0 && (
            <div className="flex items-center gap-2">
              <span className="text-xs text-slate-500 font-medium">Load from Idea:</span>
              <select
                value={selectedIdeaId}
                onChange={(e) => handleIdeaSelect(e.target.value)}
                className="bg-slate-50 border border-slate-200 text-slate-800 text-xs rounded-xl px-3 py-1.5 font-semibold focus:outline-none focus:ring-2 focus:ring-purple-500"
              >
                {ideas.map((idea) => (
                  <option key={idea.id} value={idea.id}>
                    {idea.name} ({idea.audience?.slice(0, 20)}...)
                  </option>
                ))}
              </select>
            </div>
          )}
        </div>

        {/* Dynamic Variable Inputs */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 text-xs">
          <div>
            <label className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-1">
              {"{{PRODUCT_NAME}}"}
            </label>
            <input
              type="text"
              value={customContext.PRODUCT_NAME}
              onChange={(e) => setCustomContext({ ...customContext, PRODUCT_NAME: e.target.value })}
              className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2 font-medium text-slate-800 focus:bg-white focus:ring-2 focus:ring-purple-500 outline-none"
            />
          </div>

          <div>
            <label className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-1">
              {"{{TARGET_AUDIENCE}}"}
            </label>
            <input
              type="text"
              value={customContext.TARGET_AUDIENCE}
              onChange={(e) => setCustomContext({ ...customContext, TARGET_AUDIENCE: e.target.value })}
              className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2 font-medium text-slate-800 focus:bg-white focus:ring-2 focus:ring-purple-500 outline-none"
            />
          </div>

          <div>
            <label className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-1">
              {"{{CORE_ADVANTAGE}}"}
            </label>
            <input
              type="text"
              value={customContext.CORE_ADVANTAGE}
              onChange={(e) => setCustomContext({ ...customContext, CORE_ADVANTAGE: e.target.value })}
              className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2 font-medium text-slate-800 focus:bg-white focus:ring-2 focus:ring-purple-500 outline-none"
            />
          </div>

          <div>
            <label className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-1">
              {"{{TECH_STACK}}"}
            </label>
            <input
              type="text"
              value={customContext.TECH_STACK}
              onChange={(e) => setCustomContext({ ...customContext, TECH_STACK: e.target.value })}
              className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2 font-medium text-slate-800 focus:bg-white focus:ring-2 focus:ring-purple-500 outline-none"
            />
          </div>
        </div>
      </div>

      {/* Dedicated Autonomous Pipeline Master Actions Bar */}
      {selectedCategory === 'autonomous-pipeline' && (
        <div className="bg-gradient-to-r from-purple-900 via-indigo-900 to-slate-900 p-6 rounded-3xl text-white border border-purple-800 shadow-xl space-y-4">
          <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
            <div className="space-y-1">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/20 border border-purple-400/30 text-purple-300 text-xs font-semibold uppercase tracking-wider">
                <PlayCircle className="w-3.5 h-3.5 text-amber-300" />
                <span>4-Stage Autonomous Build Sequence</span>
              </div>
              <h2 className="text-xl sm:text-2xl font-black text-white">
                Step-by-Step Autonomous Runbook for {customContext.PRODUCT_NAME}
              </h2>
              <p className="text-xs sm:text-sm text-slate-300 font-medium max-w-2xl">
                Execute these 4 prompt phases sequentially with your AI assistant (AntiGravity, Claude Code, or Cursor) to build, test, and launch without hallucinations or architectural drift.
              </p>
            </div>

            <div className="flex flex-wrap items-center gap-3 shrink-0">
              <button
                onClick={() => handleCopy('all-pipeline', fullPipelineMarkdown)}
                className="px-4 py-3 rounded-2xl bg-purple-600 hover:bg-purple-500 text-white text-xs font-extrabold transition-all flex items-center gap-2 shadow-lg shadow-purple-600/30 active:scale-95 cursor-pointer"
              >
                {copiedKey === 'all-pipeline' ? <Check className="w-4 h-4 text-emerald-300" /> : <Copy className="w-4 h-4" />}
                <span>{copiedKey === 'all-pipeline' ? 'Complete Pipeline Copied!' : 'Copy Full 4-Phase Pipeline'}</span>
              </button>

              <button
                onClick={handleDownloadFullPipeline}
                className="px-4 py-3 rounded-2xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-extrabold border border-slate-700 transition-all flex items-center gap-2 active:scale-95 cursor-pointer"
              >
                <Download className="w-4 h-4" />
                <span>Download Pipeline (.MD)</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Main Studio Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Left: Prompt Catalog & Search */}
        <div className="lg:col-span-5 space-y-4">
          {/* Search Bar */}
          <div className="relative">
            <Search className="w-4 h-4 absolute left-3.5 top-3 text-slate-400" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search prompts, categories, or tags..."
              className="w-full pl-9 pr-4 py-2.5 bg-white border border-slate-200 rounded-2xl text-xs focus:outline-none focus:ring-2 focus:ring-purple-500 shadow-sm"
            />
          </div>

          {/* Category Filter Pills */}
          <div className="flex flex-wrap gap-1.5">
            {PROMPT_CATEGORIES.map((cat) => (
              <button
                key={cat.id}
                onClick={() => setSelectedCategory(cat.id)}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all border ${
                  selectedCategory === cat.id
                    ? 'bg-purple-600 text-white border-purple-600 shadow-xs'
                    : 'bg-white text-slate-600 border-slate-200 hover:bg-slate-50'
                }`}
              >
                {cat.label}
              </button>
            ))}
          </div>

          {/* Prompt Cards List */}
          <div className="space-y-2.5 max-h-[600px] overflow-y-auto pr-1">
            {filteredPrompts.map((p) => {
              const isSelected = p.id === activePrompt.id;
              return (
                <div
                  key={p.id}
                  onClick={() => setSelectedPromptId(p.id)}
                  className={`p-4 rounded-2xl border transition-all cursor-pointer text-left space-y-2 ${
                    isSelected
                      ? 'bg-purple-50/70 border-purple-300 shadow-sm ring-1 ring-purple-400/50'
                      : 'bg-white border-slate-200/80 hover:border-purple-200 hover:shadow-xs'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] font-extrabold uppercase tracking-wider text-purple-700 bg-purple-100/70 px-2 py-0.5 rounded-full">
                      {p.badge}
                    </span>
                    <div className="flex items-center gap-1 text-[10px] font-mono text-slate-400">
                      {p.targetTools.slice(0, 2).join(' • ')}
                    </div>
                  </div>

                  <h3 className="text-sm font-bold text-slate-900 leading-snug">
                    {p.title}
                  </h3>

                  <p className="text-xs text-slate-500 line-clamp-2 leading-relaxed">
                    {p.description}
                  </p>

                  <div className="flex flex-wrap gap-1 pt-1">
                    {p.tags.slice(0, 3).map((tag, idx) => (
                      <span key={idx} className="text-[9px] font-medium bg-slate-100 text-slate-600 px-1.5 py-0.5 rounded">
                        #{tag}
                      </span>
                    ))}
                  </div>
                </div>
              );
            })}

            {filteredPrompts.length === 0 && (
              <div className="text-center py-12 bg-white rounded-2xl border border-slate-200 text-slate-400 text-xs">
                No prompts found matching your search.
              </div>
            )}
          </div>
        </div>

        {/* Right: Active Prompt Playground & Exporter */}
        <div className="lg:col-span-7 space-y-4">
          <div className="bg-slate-900 rounded-3xl p-6 text-white shadow-xl space-y-4 border border-slate-800">
            {/* Header with Title & Token Estimate */}
            <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-4">
              <div>
                <span className="text-[10px] font-extrabold text-purple-400 bg-purple-950/80 border border-purple-800/80 px-2.5 py-0.5 rounded-full uppercase tracking-wider">
                  Ready to Run
                </span>
                <h2 className="text-lg font-black text-white mt-1">
                  {activePrompt.title}
                </h2>
              </div>

              <div className="flex items-center gap-2">
                <span className="text-[11px] font-mono text-slate-400 bg-slate-800 px-2.5 py-1 rounded-lg border border-slate-700">
                  ~{estimatedTokens} tokens
                </span>
                <button
                  onClick={() => handleCopy('main-prompt', renderedPromptText)}
                  className="bg-purple-600 hover:bg-purple-500 text-white text-xs font-bold px-4 py-2 rounded-xl transition-all flex items-center gap-1.5 shadow-md shadow-purple-600/30 active:scale-95"
                >
                  {copiedKey === 'main-prompt' ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-300" />
                      <span>Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Copy Prompt</span>
                    </>
                  )}
                </button>
              </div>
            </div>

            {/* Syntax Highlighted Prompt Textarea */}
            <div className="relative">
              <pre className="text-xs font-mono text-slate-200 bg-slate-950 p-5 rounded-2xl overflow-x-auto leading-relaxed border border-slate-800 max-h-[480px] whitespace-pre-wrap selection:bg-purple-600 selection:text-white">
                {renderedPromptText}
              </pre>
            </div>

            {/* Tool-Specific Quick Copy Actions */}
            <div className="pt-2 flex flex-wrap items-center justify-between gap-3 border-t border-slate-800">
              <div className="text-xs text-slate-400 font-medium">
                Copy optimized wrapper for:
              </div>

              <div className="flex flex-wrap gap-2">
                <button
                  onClick={() => handleCopy('tool-antigravity', `[GOAL: ${activePrompt.title}]\n${renderedPromptText}\n\n[CONSTITUTION: Enforce AGENTS.md 4-File Parity]`)}
                  className="text-xs bg-slate-800 hover:bg-slate-700 text-slate-200 px-3 py-1.5 rounded-xl border border-slate-700 font-semibold transition-colors flex items-center gap-1"
                >
                  {copiedKey === 'tool-antigravity' ? <Check className="w-3 h-3 text-emerald-400" /> : <Terminal className="w-3 h-3 text-purple-400" />}
                  <span>AntiGravity</span>
                </button>

                <button
                  onClick={() => handleCopy('tool-claude', `claude "${renderedPromptText.replace(/"/g, '\\"')}"`)}
                  className="text-xs bg-slate-800 hover:bg-slate-700 text-slate-200 px-3 py-1.5 rounded-xl border border-slate-700 font-semibold transition-colors flex items-center gap-1"
                >
                  {copiedKey === 'tool-claude' ? <Check className="w-3 h-3 text-emerald-400" /> : <Code2 className="w-3 h-3 text-orange-400" />}
                  <span>Claude Code CLI</span>
                </button>

                <button
                  onClick={() => handleCopy('tool-cursor', `/* @cursor-prompt */\n${renderedPromptText}`)}
                  className="text-xs bg-slate-800 hover:bg-slate-700 text-slate-200 px-3 py-1.5 rounded-xl border border-slate-700 font-semibold transition-colors flex items-center gap-1"
                >
                  {copiedKey === 'tool-cursor' ? <Check className="w-3 h-3 text-emerald-400" /> : <Layers className="w-3 h-3 text-sky-400" />}
                  <span>Cursor Composer</span>
                </button>
              </div>
            </div>
          </div>

          {/* Builder Tip Box */}
          <div className="p-4 rounded-2xl bg-purple-50/70 border border-purple-100 text-slate-700 text-xs space-y-1">
            <span className="font-bold text-slate-900 flex items-center gap-1.5">
              <CheckCircle2 className="w-4 h-4 text-purple-600" />
              Pro Tip for 2026 AI Product Builders
            </span>
            Paste these prompts directly into the AI agent's chat without pre-editing. The variables have already been synchronized with your active workspace context.
          </div>
        </div>
      </div>
    </div>
  );
}
